epochs: 250
grad_bound: 5.0
log_frequency: 50

dataset:
  name: WebVisionDatasetLoader
  setting: 'mini'
  train_batch_size: 512
  eval_batch_size: 1024
  train_data_path: '/var/local/tmp/datasets/'
  valid_data_path: '/var/local/tmp/datasets/ILSVR2012'
  num_of_workers: 8

model:
  name: resnet50
  num_classes: 50

optimizer:
  name: SGD
  lr: 0.4
  weight_decay: 3.e-5
  momentum: 0.9
  nesterov: True

scheduler:
  name: StepLR
  step_size: 1
  gamma: 0.97

criterion:
  name: SCELoss
  num_classes: 50
  alpha: 10.0
  beta: 1.0
