epochs: 120
grad_bound: 5.0
log_frequency: 100

dataset:
  name: DatasetGenerator
  asym: False
  train_batch_size: 128
  eval_batch_size: 128
  data_path: ../datasets/
  dataset_type: 'CIFAR10'
  num_of_workers: 8

model:
  name: ToyModel
  type: $dataset.dataset_type

optimizer:
  name: SGD
  lr: 0.01
  weight_decay: 1.e-4
  momentum: 0.9

scheduler:
  name: CosineAnnealingLR
  T_max: $epochs
  eta_min: 0.0

criterion:
  name: GeneralizedCrossEntropy
  num_classes: 10
  q: 0.7
