epochs: 200
grad_bound: 5.0
log_frequency: 200

dataset:
  name: DatasetGenerator
  asym: True
  train_batch_size: 128
  eval_batch_size: 256
  data_path: ../datasets/
  dataset_type: 'CIFAR100'
  num_of_workers: 8

model:
  name: ResNet50
  num_classes: 100

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 1.e-5
  momentum: 0.9

scheduler:
  name: CosineAnnealingLR
  T_max: $epochs
  eta_min: 0.0

criterion:
  name: FocalLoss
  gamma: 0.5
